---
title: "R Notebook"
output: html_notebook
---

Get libraries
```{r, results = FALSE}
library(shiny)
library(plotly)
library(ggplot2)
library(dplyr)
library(rpart)
library(rpart.plot)
```


Load in data
```{r}
#Load in data as a dataframe called CalwData
load('CalwData.RData')
#Convert reportDate from string to actual date factor
CalwData$reportDate <- as.Date(CalwData$reportDate, "%Y-%m-%d")
```

Get table values for the relationship between each symptom
```{r}
summary(CalwData[c('variant','symptoms.symptomatic','symptoms.fever','symptoms.feelingIll','symptoms.shivering','symptoms.chillsSweats','symptoms.musclePain','symptoms.headache','symptoms.cough','symptoms.difficultyBreathing','symptoms.runnyNose','symptoms.diarrhea','symptoms.nausea','symptoms.lossOfTaste','symptoms.lossOfSmell')])

```


```{r}
dat <- CalwData[c('variant','sex','symptoms.symptomatic','symptoms.fever','symptoms.feelingIll','symptoms.shivering','symptoms.chillsSweats','symptoms.musclePain','symptoms.headache','symptoms.cough','symptoms.difficultyBreathing','symptoms.runnyNose','symptoms.diarrhea','symptoms.nausea','symptoms.lossOfTaste','symptoms.lossOfSmell')]
#dat <- CalwData[c('variant','symptoms.symptomatic','symptoms.feelingIll','symptoms.headache','symptoms.difficultyBreathing','symptoms.runnyNose','symptoms.lossOfTaste','symptoms.lossOfSmell')]

# Change NA variants and symptoms to 'unknown'
#dat$variant[is.na(dat$variant)] <- 'unknown'
dat[is.na(dat)] <- 'unknown'

# Remove people who are asymptomatic
dat_symp <- filter(dat, symptoms.symptomatic == 'yes')
dat_symp <- subset(dat_symp, select = -symptoms.symptomatic )

# Seperate unknown/NA from B117 and noVOC (omit B1351 due to there only being 4 entries)
#NOTE, NOT MAKING A COPY
dat_know <- droplevels(filter(dat_symp, variant == 'B117' | variant == 'noVOC'))
dat_unknown <- droplevels(filter(dat_symp, variant == 'B117' | variant == 'noVOC'))

```

```{r}
library(randomForest)
#Random forest schenanagains https://www.blopig.com/blog/2017/04/a-very-basic-introduction-to-random-forests-using-r/
set.seed(17)

indexes <- sample(1:nrow(dat_know), size=floor(nrow(dat_know)/5))

training <- dat_know[-indexes,]
validation1 <- dat_know[indexes,]

rf_classifier = randomForest(variant ~ ., data=training, ntree=200, mtry=12, importance=TRUE)
rf_classifier
#predict(rf_classifier, validation1)

```

```{r}
varImpPlot(rf_classifier)
```

```{r}
library(e1071)

svm_classifier = svm(variant ~ sex + symptoms.fever + symptoms.feelingIll + symptoms.shivering + symptoms.chillsSweats + symptoms.musclePain + symptoms.headache + symptoms.cough + symptoms.difficultyBreathing + symptoms.runnyNose + symptoms.diarrhea + symptoms.nausea + symptoms.lossOfTaste + symptoms.lossOfSmell, data=training)

y_pred = predict(svm_classifier, newdata = subset(validation1,select = -variant))
table(validation1$variant, y_pred)
```


```{r}
# Try with svm instead https://www.rdocumentation.org/packages/e1071/versions/1.7-6/topics/svm
library(e1071)

dat <- CalwData[c('variant','sex','symptoms.symptomatic','symptoms.fever','symptoms.feelingIll','symptoms.shivering','symptoms.chillsSweats','symptoms.musclePain','symptoms.headache','symptoms.cough','symptoms.difficultyBreathing','symptoms.runnyNose','symptoms.diarrhea','symptoms.nausea','symptoms.lossOfTaste','symptoms.lossOfSmell')]

# Change NA variants and symptoms to 'unknown'
#dat$variant[is.na(dat$variant)] <- 'unknown'
dat[is.na(dat)] <- 'unknown'

# Remove people who are asymptomatic
dat_symp <- filter(dat, symptoms.symptomatic == 'yes')

# Seperate unknown/NA from B117 and noVOC (omit B1351 due to there only being 4 entries)
#NOTE, NOT MAKING A COPY
dat_know <- droplevels(filter(dat_symp, variant == 'B117' | variant == 'noVOC'))
dat_unknown <- droplevels(filter(dat_symp, variant == 'B117' | variant == 'noVOC'))


#

# make model
model <- svm(variant ~ ., data=subset(training,select=-symptoms.symptomatic))

```

```{r}
predict(model, validation1)
```







```{r}
#Read in data csv

dat <- read.csv('7di-rl-by-ags.csv')
dat$time_iso8601 <- as.Date(dat$time_iso8601,"%Y-%m-%dT")
pal <- colorNumeric("viridis", NULL)
```


```{r}
#Second time's the charm... based off of https://github.com/jgehrcke/covid-19-germany-gae/blob/master/tools/heatmap.py
#https://rstudio.github.io/leaflet/json.html

nycounties <- rgdal::readOGR("DE-counties.geojson")

leaflet(nycounties) %>%
addTiles() %>%
addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 0.7,
fillColor = ~pal(log10(unlist(dat[10,-1],use.names = FALSE)+1)),
label = ~paste0(GEN, ": ", formatC(unlist(dat[10,],use.names = FALSE)+1, big.mark = ","))) %>%
addLegend(pal = pal, title='new cases per 1000 in last 7 days',values = ~log10(unlist(dat[10,],use.names = FALSE)+1), opacity = 1.0,
labFormat = labelFormat(transform = function(x) round(10^x)))
```





Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.
